apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "rabbitmq.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc  }}
  {{- end }}


