apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.configmapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "rabbitmq.labels" . | nindent 4 }}
data:
{{/*  host: {{ .Chart.Name }}-service.{{ .Release.Namespace }}.svs.cluster.local*/}}
  port: {{ .Values.service.ports.port | quote }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

