apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "rabbitmq.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}


