apiVersion: v1
kind: Service
metadata:
  name: {{ include "flower.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "flower.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "flower.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}

