apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery-worker.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "celery-worker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
{{- include "celery-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "celery-worker.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.global.images.api.repository }}:{{ .Values.global.images.api.tag }}
          ports:
            - containerPort: {{ .Values.service.ports.port }}
          command: {{ .Values.deployment.command | toJson }}
          args: {{ .Values.deployment.args | toJson }}
          env:
            {{- range $alias, $mapping := .Values.deployment.env.config }}
            {{- range $key, $val := $mapping }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ index $.Values.global.config $alias }}
                  key: {{ $val }}
            {{- end }}
            {{- end }}
            {{- range $alias, $mapping := .Values.deployment.env.secret }}
            {{- range $key, $val := $mapping }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ index $.Values.global.secret $alias }}
                  key: {{ $val }}
            {{- end }}
            {{- end }}
            {{ range $key, $value := .Values.deployment.env.values }}
            - name: {{ $key }}
              value: {{ $value }}
            {{ end }}
